apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: mahafdah/order-api:1.2
        ports:
        - containerPort: 80
        env:
         - name: ConnectionStrings__Default
           valueFrom:
              configMapKeyRef:
                 name: database-connection-string
                 key: mssql-connection-string-configmap 
