apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: mahafdah/order-api:v1.#{Build.BuildId}#
        #image: mahafdah/order-api:1.2
        ports:
        - containerPort: 80
        env:
         - name: ConnectionStrings__Default
           valueFrom:
              secretKeyRef:
                 name: mssql-secret
                 key: database-connection-string-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
