kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-1gb-{{ .Values.buildId }} # each PVC should reference only one StorageClass
  namespace: {{ .Values.namespace }}
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mssql-pv-claim
#   namespace: {{ .Values.namespace }}
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: order-api-azure-disk
#   resources:
#     requests:
#       storage: 1Gi
