apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: {{ .Values.namespace }}
data:
  database-connection-string-secret: UGFzc3dvcmQ9UEBzc3cwcmQ7UGVyc2lzdCBTZWN1cml0eSBJbmZvPVRydWU7VXNlciBJRD1zYTtJbml0aWFsIENhdGFsb2c9T3JkZXJzO0RhdGEgU291cmNlPW1zc3FsLXNlcnZpY2U=
type: Opaque