apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.sql.image.replicaCount }}
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      hostname: mssqlinst
      securityContext:
        fsGroup: 1000
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        # {{ .Values.sql.image.dockerHubId }}/{{ .Values.sql.image.name }}:{{ .Values.sql.image.tag }}
        ports:
        - containerPort: {{ .Values.sql.port }}
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "P@ssw0rd"
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-pv-claim