apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: order-api
spec:
  replicas: {{ .Values.web.image.replicaCount }}
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: {{ .Values.web.image.dockerHubId }}/{{ .Values.web.image.name }}:{{ .Values.web.image.tag }}
        #image: mahafdah/order-api:1.2
        ports:
        - containerPort:  {{ .Values.web.port }}
        env:
         - name: ConnectionStrings__Default
           valueFrom:
              secretKeyRef:
                 name: mssql-secret
                 key: database-connection-string-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
  type: LoadBalancer
